# Basic
title: GSNICE
subtitle: 上善若水，人淡如菊
welcome_message: 欢迎访问我的技术空间
description: 嗨，我是郭承斌 (Gavin.Guo)，一名 iOS 开发者。
creator: <a href="http://gsnice.com">@GSNICE</a>

url: "https://gsnice.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: CSDN, description: 我的 CSDN 博客, url: '//blog.csdn.net/u012439446'}
    - {title: 简历, description: 简历, url: '/resume'}
    - {title: 关于, description: 关于, url: '/about'}

# Pagination
plugins: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: GSNICE
    # duoshuo:
# Social
social:
    weibo: dgnice
    github: GSNICE
    # twitter: onevcat
    mail: sdjngcb@gmail.com

# Gitment
comment_gitment_repo: gsnice.github.io
comment_gitment_clientId: 0ca3adf35ed2617c6606
comment_gitment_clientSecret: 246be9b028fe948fcffeda798bbaafc9d9f47695

baidu-analysis: f532c5e4ec89f2b7a2b2542676d1331a

